/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/room.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.41, 0.86, 3.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf.geometry}
          material={materials["Material.039"]}
          position={[0, 0.5, 0]}
          scale={0.87}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem.geometry}
          material={materials["Material.035"]}
          position={[0, 0.01, 0]}
          scale={0.62}
        />
      </group>
      <group position={[1.45, 0.86, 3.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf001.geometry}
          material={materials["Material.040"]}
          position={[0, 0.5, 0]}
          scale={0.88}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem001.geometry}
          material={materials["Material.036"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.55, 0.62]}
        />
      </group>
      <group position={[1.35, 0.86, 3.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf002.geometry}
          material={materials["Material.038"]}
          position={[0, 0.5, 0]}
          scale={0.88}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem002.geometry}
          material={materials["Material.037"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.42, 0.62]}
        />
      </group>
      <group position={[1.38, 0.86, 3.95]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf003.geometry}
          material={materials["Material.042"]}
          position={[0, 0.5, 0]}
          scale={0.88}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem003.geometry}
          material={materials["Material.041"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.42, 0.62]}
        />
      </group>
      <group position={[1.36, 0.85, 3.96]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf004.geometry}
          material={materials["Material.030"]}
          position={[0, 0.24, 0]}
          scale={0.82}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem004.geometry}
          material={materials["Material.029"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.2, 0.62]}
        />
      </group>
      <group position={[1.44, 0.85, 3.96]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf005.geometry}
          material={materials["Material.072"]}
          position={[0, 0.24, 0]}
          scale={0.82}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem005.geometry}
          material={materials["Material.032"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.2, 0.62]}
        />
      </group>
      <group position={[1.4, 0.85, 3.96]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Leaf007.geometry}
          material={materials["Material.033"]}
          position={[0, 0.24, 0]}
          scale={0.82}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant006_Stem007.geometry}
          material={materials["Material.034"]}
          position={[0, 0.01, 0]}
          scale={[0.62, 0.2, 0.62]}
        />
      </group>
      <group position={[2.15, 0.86, 3.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Leaf.geometry}
          material={materials["Material.049"]}
          position={[0, 0.1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Stem.geometry}
          material={materials["Material.050"]}
          position={[0, 0.14, 0]}
          scale={[0.54, 0.37, 0.54]}
        />
      </group>
      <group position={[2.17, 0.82, 3.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Leaf001.geometry}
          material={materials["Material.052"]}
          position={[0, 0.1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Stem001.geometry}
          material={materials["Material.051"]}
          position={[0, 0.14, 0]}
          scale={[0.54, 0.27, 0.54]}
        />
      </group>
      <group position={[0.48, 0.86, 3.95]} rotation={[Math.PI, -0.97, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Leaf002.geometry}
          material={materials["Material.048"]}
          position={[0, 0.1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Stem002.geometry}
          material={materials["Material.047"]}
          position={[0, 0.14, 0]}
          scale={[0.54, 0.37, 0.54]}
        />
      </group>
      <group position={[0.47, 0.82, 3.96]} rotation={[Math.PI, -0.97, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Leaf003.geometry}
          material={materials["Material.045"]}
          position={[0, 0.1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant004_Stem003.geometry}
          material={materials["Material.046"]}
          position={[0, 0.14, 0]}
          scale={[0.54, 0.27, 0.54]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials["Material.022"]}
        position={[0.5, -1.13, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LWall.geometry}
        material={materials["Material.023"]}
        position={[-1.5, 1.5, 2.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RWall.geometry}
        material={materials["Material.001"]}
        position={[-1.6, 0.3, -0.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials["Material.011"]}
        position={[-2, 3, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk.geometry}
        material={materials["Material.015"]}
        position={[-1.26, 0.33, -0.53]}
        scale={[1, 0.06, 2.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials["Material.064"]}
        position={[1.1, -0.8, -1.68]}
        rotation={[0, 0.27, 0]}
        scale={[0.74, 0.37, 0.74]}
      >
        <mesh
          receiveShadow
          geometry={nodes.Chair_Seat.geometry}
          material={materials["Material.066"]}
          position={[0, 1.88, 0]}
          scale={[0.34, 0.08, 0.34]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Stem.geometry}
          material={materials["Material.065"]}
          position={[0, 0.31, 0]}
          scale={[0.76, 1.52, 0.76]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor.geometry}
        material={materials["Material.019"]}
        position={[-1.48, 0.64, -2.17]}
        rotation={[0, -0.26, 0]}
        scale={[0.25, 0.02, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor001.geometry}
        material={materials["Material.021"]}
        position={[-1.48, 0.64, 0.82]}
        rotation={[0, 0.26, 0]}
        scale={[0.25, 0.02, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor002.geometry}
        material={materials["Material.020"]}
        position={[-1.68, 0.64, -0.67]}
        scale={[0.25, 0.02, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Books.geometry}
        material={materials["Material.013"]}
        position={[-2.04, 3.25, -1.29]}
        scale={[0.2, 0.25, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Balcony.geometry}
        material={materials["Material.070"]}
        position={[0.5, -1.13, 5.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door.geometry}
        material={materials["Material.027"]}
        position={[1, -1.25, 2.44]}
        scale={[0.75, 1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Controller.geometry}
        material={materials["Material.014"]}
        position={[-2.21, 3.17, -0.95]}
        rotation={[-Math.PI / 2, 0.97, 0]}
        scale={1.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant1.geometry}
        material={materials["Material.010"]}
        position={[-2.02, 3.13, 0.26]}
        rotation={[0, 0.08, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf.geometry}
          material={materials["Material.002"]}
          position={[0, 0.2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf001.geometry}
          material={materials["Material.003"]}
          position={[-0.01, 0.2, 0.01]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard.geometry}
        material={materials["Material.067"]}
        position={[-0.7, 0.66, -0.48]}
        rotation={[0, 0.07, 0]}
        scale={[0.2, 0.03, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PC_Tower.geometry}
        material={materials["Material.018"]}
        position={[-1, -0.31, 0.94]}
        scale={[20, 20, 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Books001.geometry}
        material={materials["Material.012"]}
        position={[-2.04, 3.25, 1.21]}
        scale={[0.2, 0.25, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={materials["Material.068"]}
        position={[-0.69, 0.71, -1.28]}
        rotation={[-Math.PI, 1.36, -Math.PI]}
        scale={[3.09, 3.09, 4.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_Matt.geometry}
        material={materials["Material.017"]}
        position={[-0.71, 0.66, -0.62]}
        scale={[16, 1, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame001.geometry}
        material={materials["Material.069"]}
        position={[-0.71, 2.28, 2.23]}
        scale={[0.6, 0.38, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant002.geometry}
        material={materials["Material.024"]}
        position={[2.94, -0.01, 1.83]}
        scale={10.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_002_Leaf.geometry}
          material={materials["Material.006"]}
          scale={0.1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_002_Leaf001.geometry}
          material={materials["Material.005"]}
          position={[0, -0.01, 0.01]}
          rotation={[0, -0.95, 0]}
          scale={0.1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_002_Leaf002.geometry}
          material={materials["Material.004"]}
          rotation={[0, -1.46, 0]}
          scale={0.1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant002_Stem.geometry}
          material={materials["Material.009"]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant002_Stem001.geometry}
          material={materials["Material.008"]}
          position={[0, -0.01, 0.01]}
          rotation={[0, -0.95, 0]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant002_Stem002.geometry}
          material={materials["Material.007"]}
          rotation={[0, -1.46, 0]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant_Stand001.geometry}
        material={materials["Material.026"]}
        position={[2.94, -0.5, 1.82]}
        rotation={[0, 0.93, 0]}
        scale={[0.17, 0.04, 0.04]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Stand.geometry}
          material={materials["Material.025"]}
          position={[-0.06, 0, 0]}
          rotation={[0, -1.57, 0]}
          scale={[4.67, 1, 0.21]}
        />
      </mesh>
      <mesh
        receiveShadow
        geometry={nodes.Contact_Form.geometry}
        material={materials["Material.054"]}
        position={[-0.63, 0.63, -2.48]}
        scale={[2.04, 1.33, 1.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mug.geometry}
        material={materials["Material.016"]}
        position={[-0.54, 0.72, 0.55]}
        rotation={[-Math.PI, 0.73, -Math.PI]}
        scale={3.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planter_Box.geometry}
        material={materials["Material.073"]}
        position={[0.97, 0.85, 3.94]}
        scale={[1.5, 0.05, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003.geometry}
        material={materials["Material.057"]}
        position={[-0.68, -0.26, 3.17]}
        scale={7.1}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant003Pot.geometry}
          material={materials["Material.028"]}
          position={[0, -0.1, 0]}
          scale={1.16}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007.geometry}
        material={materials["Material.043"]}
        position={[1.12, 0.85, 3.9]}
        rotation={[0, -0.15, 0]}
        scale={3.21}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007001.geometry}
          material={materials["Material.044"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007006.geometry}
        material={materials["Material.076"]}
        position={[0.83, 0.85, 3.99]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007002.geometry}
        material={materials["Material.053"]}
        position={[0.83, 0.85, 3.99]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007003.geometry}
        material={materials["Material.075"]}
        position={[0.83, 0.85, 3.99]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007004.geometry}
          material={materials["Material.077"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007005.geometry}
        material={materials["Material.055"]}
        position={[1.87, 0.85, 3.86]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007009.geometry}
        material={materials["Material.058"]}
        position={[0.11, 0.85, 3.84]}
        rotation={[0, 0.47, 0]}
        scale={3.21}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007010.geometry}
          material={materials["Material.059"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007011.geometry}
        material={materials["Material.079"]}
        position={[1.87, 0.85, 3.86]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007012.geometry}
          material={materials["Material.078"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007013.geometry}
        material={materials["Material.060"]}
        position={[-0.17, 0.85, 4]}
        rotation={[0, 1.43, 0]}
        scale={2.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007014.geometry}
          material={materials["Material.061"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant007015.geometry}
        material={materials["Material.062"]}
        position={[-0.37, 0.85, 3.82]}
        rotation={[-Math.PI, 1.14, -Math.PI]}
        scale={2.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant007016.geometry}
          material={materials["Material.063"]}
          rotation={[-0.01, -0.69, -0.01]}
          scale={0.82}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf001.geometry}
        material={materials["Material.074"]}
        position={[-0.65, -0.47, 3.02]}
        rotation={[1.33, 0, 0.17]}
        scale={1.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf002.geometry}
        material={materials["Material.074"]}
        position={[-0.64, -0.46, 3.08]}
        rotation={[1.53, -0.08, 0.32]}
        scale={1.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf003.geometry}
        material={materials["Material.074"]}
        position={[-0.51, -0.48, 3.05]}
        rotation={[1.37, -0.16, 0.99]}
        scale={1.57}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf004.geometry}
        material={materials["Material.074"]}
        position={[-0.47, -0.48, 3.14]}
        rotation={[1.63, -0.27, 1.49]}
        scale={1.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf005.geometry}
        material={materials["Material.074"]}
        position={[-0.58, -0.46, 3.17]}
        rotation={[1.48, -0.16, 1.41]}
        scale={1.53}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf006.geometry}
        material={materials["Material.074"]}
        position={[-0.52, -0.47, 3.24]}
        rotation={[1.49, -0.14, 1.66]}
        scale={1.58}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf007.geometry}
        material={materials["Material.074"]}
        position={[-0.48, -0.48, 3.23]}
        rotation={[1.58, -0.01, 1.78]}
        scale={1.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf008.geometry}
        material={materials["Material.074"]}
        position={[-0.58, -0.47, 3.27]}
        rotation={[1.52, -0.28, 2.32]}
        scale={1.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf009.geometry}
        material={materials["Material.074"]}
        position={[-0.55, -0.48, 3.33]}
        rotation={[1.72, -0.14, 2.46]}
        scale={1.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf010.geometry}
        material={materials["Material.074"]}
        position={[-0.59, -0.47, 3.29]}
        rotation={[1.72, 0, 2.61]}
        scale={1.51}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf011.geometry}
        material={materials["Material.074"]}
        position={[-0.67, -0.48, 3.37]}
        rotation={[1.67, 0.11, 3.08]}
        scale={1.58}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf012.geometry}
        material={materials["Material.074"]}
        position={[-0.69, -0.47, 3.32]}
        rotation={[1.58, 0.01, -3.01]}
        scale={1.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf013.geometry}
        material={materials["Material.074"]}
        position={[-0.7, -0.48, 3.37]}
        rotation={[1.88, -0.02, 3.08]}
        scale={1.44}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf014.geometry}
        material={materials["Material.074"]}
        position={[-0.75, -0.47, 3.3]}
        rotation={[1.82, 0.1, -2.67]}
        scale={1.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf015.geometry}
        material={materials["Material.074"]}
        position={[-0.71, -0.45, 3.2]}
        rotation={[1.84, 0.16, -2.35]}
        scale={1.49}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf016.geometry}
        material={materials["Material.074"]}
        position={[-0.79, -0.47, 3.31]}
        rotation={[1.7, 0.3, -2.59]}
        scale={1.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf017.geometry}
        material={materials["Material.074"]}
        position={[-0.74, -0.46, 3.25]}
        rotation={[1.72, 0.06, -2.51]}
        scale={1.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf018.geometry}
        material={materials["Material.074"]}
        position={[-0.85, -0.48, 3.26]}
        rotation={[1.85, 0.23, -2.15]}
        scale={1.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf019.geometry}
        material={materials["Material.074"]}
        position={[-0.72, -0.45, 3.19]}
        rotation={[1.61, 0.13, -1.69]}
        scale={1.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf020.geometry}
        material={materials["Material.074"]}
        position={[-0.88, -0.48, 3.18]}
        rotation={[1.7, -0.03, -1.72]}
        scale={1.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf021.geometry}
        material={materials["Material.074"]}
        position={[-0.81, -0.47, 3.2]}
        rotation={[1.62, 0.18, -1.84]}
        scale={1.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf022.geometry}
        material={materials["Material.074"]}
        position={[-0.8, -0.46, 3.17]}
        rotation={[1.47, 0.11, -1.49]}
        scale={1.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf023.geometry}
        material={materials["Material.074"]}
        position={[-0.88, -0.48, 3.15]}
        rotation={[1.69, 0.32, -1.55]}
        scale={1.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf024.geometry}
        material={materials["Material.074"]}
        position={[-0.8, -0.46, 3.13]}
        rotation={[1.57, 0.08, -1.08]}
        scale={1.61}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf025.geometry}
        material={materials["Material.074"]}
        position={[-0.69, -0.44, 3.17]}
        rotation={[1.43, 0.33, -1]}
        scale={1.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf026.geometry}
        material={materials["Material.074"]}
        position={[-0.8, -0.48, 3.01]}
        rotation={[1.43, 0.15, -0.6]}
        scale={1.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf027.geometry}
        material={materials["Material.074"]}
        position={[-0.83, -0.48, 3.01]}
        rotation={[1.29, 0.25, -0.71]}
        scale={1.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf028.geometry}
        material={materials["Material.074"]}
        position={[-0.7, -0.46, 3.1]}
        rotation={[1.38, 0.13, -0.14]}
        scale={1.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf029.geometry}
        material={materials["Material.074"]}
        position={[-0.72, -0.48, 2.98]}
        rotation={[1.41, 0, -0.14]}
        scale={1.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003_Leaf030.geometry}
        material={materials["Material.074"]}
        position={[-0.7, -0.46, 3.05]}
        rotation={[1.49, 0.17, -0.18]}
        scale={1.44}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-1.22, 2.75, 2.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FrameTray.geometry}
        material={materials["Material.071"]}
        position={[-0.32, 1.03, 2.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Marker001.geometry}
        material={materials["Material.056"]}
        position={[-0.78, 1.05, 2.17]}
        rotation={[Math.PI / 2, 0, -1.5]}
        scale={0.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Marker002.geometry}
        material={materials["Material.031"]}
        position={[-1.08, 1.05, 2.15]}
        rotation={[Math.PI / 2, 0, -1.67]}
        scale={0.18}
      />
    </group>
  );
}

useGLTF.preload("/room.gltf");
